---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wms-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wms-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: wms-mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: wms-microservice
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wms-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wms-microservice
  template:
    metadata:
      labels:
        app: wms-microservice
    spec:
      containers:
        - name: mysql
          image: mysql:8.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: wms-user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: wms
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: wms-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: wms-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: wms-mysql-pv-claim
