apiVersion: v1
kind: Service
metadata:
  name: wms-whisper-service
  labels:
    app: whisper-microservice
spec:
  type: LoadBalancer
  selector:
    app: whisper-microservice
  ports:
    - port: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wms-whisper-deployment
  labels:
    app: whisper-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whisper-microservice
  template:
    metadata:
      labels:
        app: whisper-microservice
    spec:
      containers:
        - name: wms-whisper-container
          image: juliusmarminge/wms-whisper:latest
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_HOST
              value: wms-mysql-service
            - name: MYSQL_DATABASE
              value: wms
